title: Maniac Productions
description: Creating music, Mix and mastering, and DJing
github_username: clemonsq5724
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
